/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesGraficas.Perfil;


import Entidades.Usuario;
import InterfacesGraficas.Login.IniciarSesion;
import Utilidades.Foto;
import Utilidades.ServiciosUsuario;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;



/**
 *
 * @author chave
 */
public class pnlPerfiles extends javax.swing.JPanel {

    /**
     * Creates new form pnlPerfiles
     */
    Usuario user;
    ServiciosUsuario servicio;
    JFrame padre;
    IniciarSesion login;
    public pnlPerfiles() throws ClassNotFoundException, SQLException {                
        initComponents();        
        this.servicio = new ServiciosUsuario();
        this.pnlSlider.setPanelNormal(pnlPerfil);
        btnVolver.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSlider = new newscomponents.RSPanelEffect();
        pnlPerfil = new javax.swing.JPanel();
        txtIdUsuario = new necesario.TextField();
        txtNombres = new necesario.TextField();
        txtCorreo = new necesario.TextField();
        txtApellidos = new necesario.TextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        lblfotoP = new javax.swing.JLabel();
        txtTelefono = new necesario.TextField();
        jLabel8 = new javax.swing.JLabel();
        txtFechaNac = new necesario.TextField();
        jLabel9 = new javax.swing.JLabel();
        btnCambiarContra = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnActualizarDatos = new RSMaterialComponent.RSButtonMaterialIconOne();
        pnlCambiarContra = new javax.swing.JPanel();
        txtConfirmar = new necesario.TextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtContraseñaActual = new necesario.TextField();
        txtNuevaContra = new necesario.TextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnGuardarContraseña = new RSMaterialComponent.RSButtonMaterialIconOne();
        lbldesigualdad = new javax.swing.JLabel();
        pnlActualizarDatos = new javax.swing.JPanel();
        txtNombre1 = new necesario.TextField();
        txtSegundoNombre = new necesario.TextField();
        txtApellidoPaterno = new necesario.TextField();
        txtApellidoMaterno = new necesario.TextField();
        txtNuevoCorreo = new necesario.TextField();
        rsNuevaFecha = new rojeru_san.rsdate.RSDateChooser();
        txtNuevoTelefono = new necesario.TextField();
        lblFoto = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnFoto = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnGuardar = new RSMaterialComponent.RSButtonMaterialIconOne();
        txtIdUsuario1 = new necesario.TextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDireccion1 = new javax.swing.JTextArea();
        btnVolver = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnCerrarSesion = new RSMaterialComponent.RSButtonMaterialIconOne();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlSlider.setBackground(new java.awt.Color(255, 255, 255));

        pnlPerfil.setBackground(new java.awt.Color(255, 255, 255));
        pnlPerfil.setName("pnlPerfil"); // NOI18N

        txtIdUsuario.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtIdUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtIdUsuario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtIdUsuario.setEnabled(false);
        txtIdUsuario.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtIdUsuario.setName("txtidUsuario"); // NOI18N
        txtIdUsuario.setPlaceholder("IdUsuario");

        txtNombres.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtNombres.setForeground(new java.awt.Color(0, 0, 0));
        txtNombres.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombres.setEnabled(false);
        txtNombres.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtNombres.setName("txtNombres"); // NOI18N
        txtNombres.setPlaceholder("Nombres");

        txtCorreo.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCorreo.setEnabled(false);
        txtCorreo.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtCorreo.setName("txtCorreo"); // NOI18N
        txtCorreo.setPlaceholder("Correo");

        txtApellidos.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtApellidos.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtApellidos.setEnabled(false);
        txtApellidos.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtApellidos.setName("txtApellidos"); // NOI18N
        txtApellidos.setPlaceholder("Apellidos");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(37, 45, 223));
        jLabel1.setText("Dni Usuario");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(37, 45, 223));
        jLabel2.setText("Apellidos");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(37, 45, 223));
        jLabel3.setText("Nombres");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(37, 45, 223));
        jLabel4.setText("Correo");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(37, 45, 223));
        jLabel5.setText("Direccion");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 108, 255));
        jLabel6.setText("PERFIL");

        txtDireccion.setColumns(20);
        txtDireccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDireccion.setLineWrap(true);
        txtDireccion.setRows(5);
        txtDireccion.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtDireccion.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDireccion.setEnabled(false);
        txtDireccion.setSelectionColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(txtDireccion);

        lblfotoP.setBackground(new java.awt.Color(255, 255, 255));
        lblfotoP.setForeground(new java.awt.Color(255, 255, 255));
        lblfotoP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblfotoP.setName("lblfoto"); // NOI18N
        lblfotoP.setOpaque(true);

        txtTelefono.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTelefono.setEnabled(false);
        txtTelefono.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtTelefono.setName("txtTelefono"); // NOI18N
        txtTelefono.setPlaceholder("Telefono");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(37, 45, 223));
        jLabel8.setText("Telefono");

        txtFechaNac.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtFechaNac.setForeground(new java.awt.Color(0, 0, 0));
        txtFechaNac.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFechaNac.setEnabled(false);
        txtFechaNac.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtFechaNac.setName("txtFechaNac"); // NOI18N
        txtFechaNac.setPlaceholder("Fecha de Nacimiento");
        txtFechaNac.setSelectionStart(10);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(37, 45, 223));
        jLabel9.setText("Fecha de Nacimiento");

        btnCambiarContra.setBackground(new java.awt.Color(204, 204, 204));
        btnCambiarContra.setText("     Cambiar Contraseña");
        btnCambiarContra.setBackgroundHover(new java.awt.Color(0, 108, 255));
        btnCambiarContra.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnCambiarContra.setForegroundText(new java.awt.Color(0, 0, 0));
        btnCambiarContra.setIconTextGap(29);
        btnCambiarContra.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ENHANCED_ENCRYPTION);
        btnCambiarContra.setName("btnCambiarContra"); // NOI18N
        btnCambiarContra.setPaddingLeft(15);
        btnCambiarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarContraActionPerformed(evt);
            }
        });

        btnActualizarDatos.setBackground(new java.awt.Color(204, 204, 204));
        btnActualizarDatos.setText("     Actualizar Datos");
        btnActualizarDatos.setToolTipText("");
        btnActualizarDatos.setBackgroundHover(new java.awt.Color(0, 108, 255));
        btnActualizarDatos.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnActualizarDatos.setForegroundText(new java.awt.Color(0, 0, 0));
        btnActualizarDatos.setIconTextGap(30);
        btnActualizarDatos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        btnActualizarDatos.setPaddingLeft(15);
        btnActualizarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPerfilLayout = new javax.swing.GroupLayout(pnlPerfil);
        pnlPerfil.setLayout(pnlPerfilLayout);
        pnlPerfilLayout.setHorizontalGroup(
            pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPerfilLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPerfilLayout.createSequentialGroup()
                        .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(btnActualizarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCambiarContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPerfilLayout.createSequentialGroup()
                        .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel8))
                        .addGap(36, 36, 36)
                        .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaNac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblfotoP, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );
        pnlPerfilLayout.setVerticalGroup(
            pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPerfilLayout.createSequentialGroup()
                .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPerfilLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6)
                        .addGap(16, 16, 16)
                        .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPerfilLayout.createSequentialGroup()
                                .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(4, 4, 4)
                                .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblfotoP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlPerfilLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(pnlPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlPerfilLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPerfilLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnActualizarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCambiarContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlSlider.add(pnlPerfil, "card2");

        pnlCambiarContra.setBackground(new java.awt.Color(255, 255, 255));
        pnlCambiarContra.setName("pnlCambiarContra"); // NOI18N

        txtConfirmar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtConfirmar.setForeground(new java.awt.Color(0, 0, 0));
        txtConfirmar.setDisabledTextColor(new java.awt.Color(37, 45, 223));
        txtConfirmar.setName("txtConfirmar"); // NOI18N
        txtConfirmar.setPlaceholder("Confirmar Contraseña");
        txtConfirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConfirmarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConfirmarKeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(37, 45, 223));
        jLabel21.setText("Confirmar Contraseña");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(37, 45, 223));
        jLabel22.setText("Contraseña Actual");

        txtContraseñaActual.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtContraseñaActual.setForeground(new java.awt.Color(0, 0, 0));
        txtContraseñaActual.setDisabledTextColor(new java.awt.Color(37, 45, 223));
        txtContraseñaActual.setName("txtContraseñaActual"); // NOI18N
        txtContraseñaActual.setPlaceholder("Contraseña Actual");

        txtNuevaContra.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtNuevaContra.setForeground(new java.awt.Color(0, 0, 0));
        txtNuevaContra.setDisabledTextColor(new java.awt.Color(37, 45, 223));
        txtNuevaContra.setName("txtNuevaContra"); // NOI18N
        txtNuevaContra.setPlaceholder("Nueva Contraseña");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(37, 45, 223));
        jLabel23.setText("Nueva Contraseña");

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 108, 255));
        jLabel24.setText("CAMBIAR CONTRASEÑA");

        btnGuardarContraseña.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardarContraseña.setText("     Guardar");
        btnGuardarContraseña.setBackgroundHover(new java.awt.Color(0, 153, 0));
        btnGuardarContraseña.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnGuardarContraseña.setForegroundText(new java.awt.Color(0, 0, 0));
        btnGuardarContraseña.setIconTextGap(29);
        btnGuardarContraseña.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ENHANCED_ENCRYPTION);
        btnGuardarContraseña.setName("btnGuardarContraseña"); // NOI18N
        btnGuardarContraseña.setPaddingLeft(15);
        btnGuardarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarContraseñaActionPerformed(evt);
            }
        });

        lbldesigualdad.setBackground(new java.awt.Color(255, 0, 0));
        lbldesigualdad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbldesigualdad.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlCambiarContraLayout = new javax.swing.GroupLayout(pnlCambiarContra);
        pnlCambiarContra.setLayout(pnlCambiarContraLayout);
        pnlCambiarContraLayout.setHorizontalGroup(
            pnlCambiarContraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCambiarContraLayout.createSequentialGroup()
                .addGroup(pnlCambiarContraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCambiarContraLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel24))
                    .addGroup(pnlCambiarContraLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(pnlCambiarContraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtContraseñaActual, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel21)
                            .addComponent(txtNuevaContra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbldesigualdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(409, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCambiarContraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGuardarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlCambiarContraLayout.setVerticalGroup(
            pnlCambiarContraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCambiarContraLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel24)
                .addGap(32, 32, 32)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContraseñaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addGap(4, 4, 4)
                .addComponent(txtNuevaContra, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addGap(4, 4, 4)
                .addComponent(txtConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbldesigualdad, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnGuardarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlSlider.add(pnlCambiarContra, "card3");

        pnlActualizarDatos.setBackground(new java.awt.Color(255, 255, 255));
        pnlActualizarDatos.setName("pnlActualizarDatos"); // NOI18N

        txtNombre1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtNombre1.setForeground(java.awt.Color.black);
        txtNombre1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre1.setAlignmentX(1.0F);
        txtNombre1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombre1.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtNombre1.setName("txtNombre1"); // NOI18N
        txtNombre1.setPlaceholder("Nombre");
        txtNombre1.setSoloLetras(true);

        txtSegundoNombre.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtSegundoNombre.setForeground(java.awt.Color.black);
        txtSegundoNombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSegundoNombre.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtSegundoNombre.setName("txtSegundoNombre"); // NOI18N
        txtSegundoNombre.setPlaceholder("Segundo Nombre");
        txtSegundoNombre.setSoloLetras(true);

        txtApellidoPaterno.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtApellidoPaterno.setForeground(java.awt.Color.black);
        txtApellidoPaterno.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtApellidoPaterno.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtApellidoPaterno.setName("txtApellidoPaterno"); // NOI18N
        txtApellidoPaterno.setPlaceholder("Apellido Paterno");
        txtApellidoPaterno.setSoloLetras(true);

        txtApellidoMaterno.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtApellidoMaterno.setForeground(java.awt.Color.black);
        txtApellidoMaterno.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtApellidoMaterno.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtApellidoMaterno.setName("txtApellidoMaterno"); // NOI18N
        txtApellidoMaterno.setPlaceholder("Apellido Materno");
        txtApellidoMaterno.setSoloLetras(true);

        txtNuevoCorreo.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtNuevoCorreo.setForeground(java.awt.Color.black);
        txtNuevoCorreo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNuevoCorreo.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtNuevoCorreo.setName("txtNuevoCorreo"); // NOI18N
        txtNuevoCorreo.setPlaceholder("Correo");

        rsNuevaFecha.setColorBackground(new java.awt.Color(0, 0, 0));
        rsNuevaFecha.setColorDiaActual(new java.awt.Color(255, 102, 102));
        rsNuevaFecha.setColorForeground(new java.awt.Color(0, 0, 0));
        rsNuevaFecha.setFormatoFecha("yyyy-MM-dd");

        txtNuevoTelefono.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtNuevoTelefono.setForeground(java.awt.Color.black);
        txtNuevoTelefono.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNuevoTelefono.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtNuevoTelefono.setName("txtNuevoTelefono"); // NOI18N
        txtNuevoTelefono.setPlaceholder("Telefono");
        txtNuevoTelefono.setSoloNumeros(true);

        lblFoto.setBackground(new java.awt.Color(255, 255, 255));
        lblFoto.setForeground(new java.awt.Color(255, 255, 255));
        lblFoto.setName("lblfoto"); // NOI18N
        lblFoto.setOpaque(true);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(37, 45, 223));
        jLabel11.setText("Telefono");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(37, 45, 223));
        jLabel12.setText("Dni Usuario");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(37, 45, 223));
        jLabel13.setText("Apellido Paterno");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(37, 45, 223));
        jLabel14.setText("Fecha de Nacimiento");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(37, 45, 223));
        jLabel15.setText("Nombre");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(37, 45, 223));
        jLabel16.setText("Correo");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(37, 45, 223));
        jLabel17.setText("Direccion");

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 108, 255));
        jLabel18.setText("ACTUALIZAR DATOS");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(37, 45, 223));
        jLabel19.setText("Segundo Nombre");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(37, 45, 223));
        jLabel20.setText("Apellido Materno");

        btnFoto.setBackground(new java.awt.Color(0, 153, 255));
        btnFoto.setText("    Subir Foto");
        btnFoto.setBackgroundHover(new java.awt.Color(0, 108, 255));
        btnFoto.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnFoto.setForegroundText(new java.awt.Color(0, 0, 0));
        btnFoto.setIconTextGap(29);
        btnFoto.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.OPEN_IN_BROWSER);
        btnFoto.setName("btnFoto"); // NOI18N
        btnFoto.setPaddingLeft(15);
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardar.setText("       Guardar");
        btnGuardar.setBackgroundHover(new java.awt.Color(0, 153, 0));
        btnGuardar.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnGuardar.setForegroundText(new java.awt.Color(0, 0, 0));
        btnGuardar.setIconTextGap(29);
        btnGuardar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.setPaddingLeft(15);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtIdUsuario1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtIdUsuario1.setForeground(java.awt.Color.black);
        txtIdUsuario1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtIdUsuario1.setEnabled(false);
        txtIdUsuario1.setMargin(new java.awt.Insets(3, 10, 3, 6));
        txtIdUsuario1.setName("txtidUsuario1"); // NOI18N
        txtIdUsuario1.setPlaceholder("IdUsuario");

        txtDireccion1.setColumns(5);
        txtDireccion1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDireccion1.setLineWrap(true);
        txtDireccion1.setRows(5);
        txtDireccion1.setWrapStyleWord(true);
        txtDireccion1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtDireccion1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(txtDireccion1);

        javax.swing.GroupLayout pnlActualizarDatosLayout = new javax.swing.GroupLayout(pnlActualizarDatos);
        pnlActualizarDatos.setLayout(pnlActualizarDatosLayout);
        pnlActualizarDatosLayout.setHorizontalGroup(
            pnlActualizarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActualizarDatosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlActualizarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlActualizarDatosLayout.createSequentialGroup()
                        .addGroup(pnlActualizarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(txtSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(pnlActualizarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNuevoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlActualizarDatosLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(162, 162, 162)
                        .addComponent(jLabel14))
                    .addComponent(jLabel18)
                    .addGroup(pnlActualizarDatosLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(199, 199, 199)
                        .addComponent(jLabel16))
                    .addGroup(pnlActualizarDatosLayout.createSequentialGroup()
                        .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(rsNuevaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlActualizarDatosLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(159, 159, 159)
                        .addComponent(jLabel11))
                    .addGroup(pnlActualizarDatosLayout.createSequentialGroup()
                        .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(txtNuevoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(pnlActualizarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActualizarDatosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlActualizarDatosLayout.setVerticalGroup(
            pnlActualizarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActualizarDatosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel18)
                .addGap(16, 16, 16)
                .addGroup(pnlActualizarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16))
                .addGap(6, 6, 6)
                .addGroup(pnlActualizarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlActualizarDatosLayout.createSequentialGroup()
                        .addGroup(pnlActualizarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlActualizarDatosLayout.createSequentialGroup()
                                .addComponent(txtIdUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel15)
                                .addGap(4, 4, 4)
                                .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel19)
                                .addGap(4, 4, 4)
                                .addComponent(txtSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlActualizarDatosLayout.createSequentialGroup()
                                .addComponent(txtNuevoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel17)
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlActualizarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)))
                    .addGroup(pnlActualizarDatosLayout.createSequentialGroup()
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pnlActualizarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlActualizarDatosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlActualizarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlActualizarDatosLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(rsNuevaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addGroup(pnlActualizarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addGroup(pnlActualizarDatosLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel11)))
                        .addGap(2, 2, 2)
                        .addGroup(pnlActualizarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNuevoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActualizarDatosLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pnlSlider.add(pnlActualizarDatos, "card4");

        btnVolver.setBackground(new java.awt.Color(204, 204, 204));
        btnVolver.setText("Volver");
        btnVolver.setBackgroundHover(new java.awt.Color(0, 108, 255));
        btnVolver.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnVolver.setForegroundText(new java.awt.Color(0, 0, 0));
        btnVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolver.setIconTextGap(29);
        btnVolver.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CHEVRON_LEFT);
        btnVolver.setName("btnVolver"); // NOI18N
        btnVolver.setPaddingLeft(15);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnCerrarSesion.setBackground(new java.awt.Color(204, 204, 204));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/32bkver.png"))); // NOI18N
        btnCerrarSesion.setText("     Cerrar Sesion");
        btnCerrarSesion.setBackgroundHover(new java.awt.Color(242, 72, 72));
        btnCerrarSesion.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnCerrarSesion.setForegroundText(new java.awt.Color(0, 0, 0));
        btnCerrarSesion.setIconTextGap(29);
        btnCerrarSesion.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLEAR);
        btnCerrarSesion.setName("btnCerrarSesion"); // NOI18N
        btnCerrarSesion.setPaddingLeft(15);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.pnlSlider.setPanelNormal(pnlPerfil);
        btnVolver.setVisible(false);
        btnCerrarSesion.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnActualizarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarDatosActionPerformed
         btnVolver.setVisible(true);
         txtIdUsuario1.setText(this.user.getDni());
        btnCerrarSesion.setVisible(false);
        this.pnlSlider.setPanelNormal(pnlActualizarDatos);
    }//GEN-LAST:event_btnActualizarDatosActionPerformed

    private void btnCambiarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarContraActionPerformed
        btnVolver.setVisible(true);
        btnCerrarSesion.setVisible(false);
        this.pnlSlider.setPanelNormal(pnlCambiarContra);

    }//GEN-LAST:event_btnCambiarContraActionPerformed

    private void btnGuardarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarContraseñaActionPerformed
   
        String contraseñaNueva =txtNuevaContra.getText();
        if(!txtContraseñaActual.getText().isEmpty()
            && !txtConfirmar.getText().isEmpty()
            && !txtNuevaContra.getText().isEmpty()){
            try {
                if(validarContraseña()){              
                    servicio.actualizarContraseña(contraseñaNueva,user.getDni());               
                    JOptionPane.showMessageDialog(null,"Se cambio la "
                            + "contraseña correctamente"); 
                    limpiarInputs();
                }
                else
                    JOptionPane.showMessageDialog(null, "La contraseña "
                            + "ingresada no es correcta"); 
            } catch (SQLException ex) {
                Logger.getLogger(pnlPerfiles.class.getName()).log(Level.SEVERE
                        , null, ex);
            }
        }
        else
             JOptionPane.showMessageDialog(null, "Completa todos los campos");
    }//GEN-LAST:event_btnGuardarContraseñaActionPerformed

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        try {      
            lblFoto.setIcon(null);
            Foto.subirFoto(lblFoto,this);
             
            
        } catch (IOException ex) {
            Logger.getLogger(pnlPerfiles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFotoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        if(!txtNombre1.getText().isEmpty()&&!txtApellidoPaterno.getText()
                .isEmpty()&& !txtApellidoMaterno.getText().isEmpty()
                &&!txtNuevoCorreo.getText().isEmpty()&&
                !txtNuevoTelefono.getText().isEmpty()&& 
                !txtDireccion1.getText().isEmpty()){            
            try {
                user.setFoto(Foto.obtenerFoto(lblFoto)); 
                setDatosUsuario();
                this.servicio.actualizarUsuario(user,user.getDni());
                cargarPerfil();
                JOptionPane.showMessageDialog(null, "Datos Actualizados");
                limpiarInputs();
            } catch (SQLException | IOException ex) {
                Logger.getLogger(pnlPerfiles.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }else
             JOptionPane.showMessageDialog(null, "Completa todos los campos.");
    }//GEN-LAST:event_btnGuardarActionPerformed
    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        login.setVisible(true);
        padre.dispose();        
    }//GEN-LAST:event_btnCerrarSesionActionPerformed
    public void cerrarConexion() throws SQLException{
        this.servicio.cerrarConexion();
    }
    private void txtConfirmarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmarKeyReleased
        if(!txtNuevaContra.getText().equals(txtConfirmar.getText()))
            lbldesigualdad.setText("Las contraseñas no son iguales.");
        else
            lbldesigualdad.setText("");
    }//GEN-LAST:event_txtConfirmarKeyReleased

    private void txtConfirmarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmarKeyTyped
        if(!txtNuevaContra.getText().equals(txtConfirmar.getText()))
            lbldesigualdad.setText("Las contraseñas no son iguales.");
        else
            lbldesigualdad.setText("");
    }//GEN-LAST:event_txtConfirmarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconOne btnActualizarDatos;
    private RSMaterialComponent.RSButtonMaterialIconOne btnCambiarContra;
    private RSMaterialComponent.RSButtonMaterialIconOne btnCerrarSesion;
    private RSMaterialComponent.RSButtonMaterialIconOne btnFoto;
    public RSMaterialComponent.RSButtonMaterialIconOne btnGuardar;
    private RSMaterialComponent.RSButtonMaterialIconOne btnGuardarContraseña;
    private RSMaterialComponent.RSButtonMaterialIconOne btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lbldesigualdad;
    private javax.swing.JLabel lblfotoP;
    private javax.swing.JPanel pnlActualizarDatos;
    private javax.swing.JPanel pnlCambiarContra;
    private javax.swing.JPanel pnlPerfil;
    private newscomponents.RSPanelEffect pnlSlider;
    private rojeru_san.rsdate.RSDateChooser rsNuevaFecha;
    private necesario.TextField txtApellidoMaterno;
    private necesario.TextField txtApellidoPaterno;
    private necesario.TextField txtApellidos;
    private necesario.TextField txtConfirmar;
    private necesario.TextField txtContraseñaActual;
    private necesario.TextField txtCorreo;
    private javax.swing.JTextArea txtDireccion;
    private javax.swing.JTextArea txtDireccion1;
    private necesario.TextField txtFechaNac;
    private necesario.TextField txtIdUsuario;
    private necesario.TextField txtIdUsuario1;
    private necesario.TextField txtNombre1;
    private necesario.TextField txtNombres;
    private necesario.TextField txtNuevaContra;
    private necesario.TextField txtNuevoCorreo;
    private necesario.TextField txtNuevoTelefono;
    private necesario.TextField txtSegundoNombre;
    private necesario.TextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    public void cargarDatos(Usuario user,JFrame padre,IniciarSesion login){
        this.user = user;
        this.login = login;
        this.padre = padre;
    }      
    public Usuario getUsuario(){
        return this.user;
    }   
    public void cargarPerfil() throws IOException {    
        txtNombres.setText(user.getNombres());
        txtApellidos.setText(user.getApellidos());
        txtCorreo.setText(user.getCorreo());
        txtIdUsuario.setText(user.getDni());
        txtTelefono.setText(user.getCelular());
        txtFechaNac.setText(user.getFechaString());
        txtDireccion.setText(user.getDireccion());
        if(user.getFoto()!=null)
            Foto.cargarFoto(lblfotoP,user.getFoto());
    }
    private boolean validarContraseña() { 
        boolean valido = false;
        if((txtContraseñaActual.getText().equals(user.getContraseña())                
                && txtConfirmar.getText().equals(txtNuevaContra.getText())))
            valido = true;
        
        return valido;
    }    
    public void limpiarInputs() {
        txtNombre1.setText("");
        txtSegundoNombre.setText("");
        txtApellidoPaterno.setText("");
        txtApellidoMaterno.setText("");
        txtNuevoCorreo.setText("");
        txtNuevoTelefono.setText("");
        txtDireccion1.setText("");
        txtContraseñaActual.setText("");
        txtNuevaContra.setText("");
        txtConfirmar.setText("");
        lblFoto.setIcon(null);
    }
    public void setDatosUsuario() throws IOException {        
        user.setDni(user.getDni());
        user.setNombres(txtNombre1.getText()
                , txtSegundoNombre.getText());
        user.setApellidos(txtApellidoPaterno.getText()
                , txtApellidoMaterno.getText());
        user.setCelular(txtNuevoTelefono.getText());
        user.setCorreo(txtNuevoCorreo.getText());
        user.setDireccion(txtDireccion1.getText());
        user.setFechaNac(rsNuevaFecha.getDatoFecha());
        user.setFoto(Foto.obtenerFoto(lblFoto));       
    }
}
