/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesGraficas.Solicitante;


import Entidades.Mensaje;
import Entidades.Usuario;
import Utilidades.ServiciosUsuario;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author chave
 */
public class pnlComentariosSolicitante extends javax.swing.JPanel {

    /**
     * Creates new form pnlComentariosSolicitante
     */
    private Usuario user;
    List<Mensaje> listaRetro ;
    ServiciosUsuario servicio;
    String tipo;
    int cod;   
    public pnlComentariosSolicitante() throws ClassNotFoundException, SQLException {
        initComponents();
        tipo = "Sugerencia";
        lblFecha2.setVisible(false);
        this.servicio = new ServiciosUsuario();
        this.pnlSliderRetro.setPanelNormal(pnlTablaRetro);
        btnVolver.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSliderRetro = new rojerusan.RSPanelEffect();
        pnlTablaRetro = new javax.swing.JPanel();
        txtBuscarRetro = new RSMaterialComponent.RSTextFieldMaterialIcon();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaRetro = new RSMaterialComponent.RSTableMetroCustom();
        btnSugerencias = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnReclamos = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnGenerar = new RSMaterialComponent.RSButtonMaterialIconOne();
        btnVisualizarRetro = new RSMaterialComponent.RSButtonMaterialIconOne();
        pnlGenerar = new javax.swing.JPanel();
        cbxTipo = new RSMaterialComponent.RSComboBoxMaterial();
        lblestado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtcontenidoRetro = new javax.swing.JTextArea();
        lblFecha = new rojeru_san.rsdate.RSLabelFecha();
        btnAceptarGenerar = new RSMaterialComponent.RSButtonMaterialIconOne();
        lblFecha2 = new javax.swing.JLabel();
        btnVolver = new RSMaterialComponent.RSButtonMaterialIconOne();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlSliderRetro.setBackground(new java.awt.Color(255, 255, 255));

        pnlTablaRetro.setBackground(new java.awt.Color(255, 255, 255));
        pnlTablaRetro.setName("pnlTablaRetro"); // NOI18N

        txtBuscarRetro.setForeground(new java.awt.Color(0, 108, 255));
        txtBuscarRetro.setColorIcon(new java.awt.Color(0, 108, 255));
        txtBuscarRetro.setColorMaterial(new java.awt.Color(0, 108, 255));
        txtBuscarRetro.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        txtBuscarRetro.setPhColor(new java.awt.Color(0, 69, 255));
        txtBuscarRetro.setPlaceholder("Buscar");
        txtBuscarRetro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarRetroKeyReleased(evt);
            }
        });

        jScrollPane3.setBorder(null);

        tablaRetro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tablaRetro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "", null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Contenido", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaRetro.setBackgoundHead(new java.awt.Color(0, 108, 255));
        tablaRetro.setBackgoundHover(new java.awt.Color(10, 94, 208));
        tablaRetro.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        tablaRetro.setColorSecondary(new java.awt.Color(255, 255, 255));
        tablaRetro.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        tablaRetro.setRowHeight(40);
        tablaRetro.setSelectionBackground(new java.awt.Color(78, 85, 230));
        jScrollPane3.setViewportView(tablaRetro);
        if (tablaRetro.getColumnModel().getColumnCount() > 0) {
            tablaRetro.getColumnModel().getColumn(1).setPreferredWidth(500);
            tablaRetro.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        btnSugerencias.setBackground(new java.awt.Color(204, 204, 204));
        btnSugerencias.setText("Sugerencias");
        btnSugerencias.setBackgroundHover(new java.awt.Color(0, 108, 255));
        btnSugerencias.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnSugerencias.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnSugerencias.setForegroundText(new java.awt.Color(0, 0, 0));
        btnSugerencias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSugerencias.setIconTextGap(29);
        btnSugerencias.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ASSISTANT);
        btnSugerencias.setPaddingLeft(15);
        btnSugerencias.setSelected(true);
        btnSugerencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSugerenciasActionPerformed(evt);
            }
        });

        btnReclamos.setBackground(new java.awt.Color(204, 204, 204));
        btnReclamos.setText("Reclamos");
        btnReclamos.setBackgroundHover(new java.awt.Color(0, 108, 255));
        btnReclamos.setForegroundIcon(new java.awt.Color(204, 0, 0));
        btnReclamos.setForegroundText(new java.awt.Color(204, 0, 0));
        btnReclamos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReclamos.setIconTextGap(29);
        btnReclamos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ANNOUNCEMENT);
        btnReclamos.setPaddingLeft(15);
        btnReclamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReclamosActionPerformed(evt);
            }
        });

        btnGenerar.setBackground(new java.awt.Color(204, 204, 204));
        btnGenerar.setText("Generar Comentario");
        btnGenerar.setBackgroundHover(new java.awt.Color(0, 108, 255));
        btnGenerar.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnGenerar.setForegroundText(new java.awt.Color(0, 0, 0));
        btnGenerar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGenerar.setIconTextGap(29);
        btnGenerar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CREATE_NEW_FOLDER);
        btnGenerar.setPaddingLeft(15);
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        btnVisualizarRetro.setBackground(new java.awt.Color(204, 204, 204));
        btnVisualizarRetro.setText("Ver Comentario");
        btnVisualizarRetro.setBackgroundHover(new java.awt.Color(0, 108, 255));
        btnVisualizarRetro.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnVisualizarRetro.setForegroundText(new java.awt.Color(0, 0, 0));
        btnVisualizarRetro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVisualizarRetro.setIconTextGap(29);
        btnVisualizarRetro.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.VISIBILITY);
        btnVisualizarRetro.setPaddingLeft(15);
        btnVisualizarRetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarRetroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTablaRetroLayout = new javax.swing.GroupLayout(pnlTablaRetro);
        pnlTablaRetro.setLayout(pnlTablaRetroLayout);
        pnlTablaRetroLayout.setHorizontalGroup(
            pnlTablaRetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaRetroLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlTablaRetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTablaRetroLayout.createSequentialGroup()
                        .addComponent(btnSugerencias, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReclamos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(txtBuscarRetro, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(pnlTablaRetroLayout.createSequentialGroup()
                        .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVisualizarRetro, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
            .addGroup(pnlTablaRetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTablaRetroLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );
        pnlTablaRetroLayout.setVerticalGroup(
            pnlTablaRetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaRetroLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlTablaRetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarRetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSugerencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReclamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 360, Short.MAX_VALUE)
                .addGroup(pnlTablaRetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisualizarRetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(pnlTablaRetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTablaRetroLayout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(82, Short.MAX_VALUE)))
        );

        pnlSliderRetro.add(pnlTablaRetro, "card3");

        pnlGenerar.setBackground(new java.awt.Color(255, 255, 255));
        pnlGenerar.setName("pnlGenerar"); // NOI18N
        pnlGenerar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sugerencia", "Reclamo" }));
        pnlGenerar.add(cbxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 107, -1, -1));

        lblestado.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblestado.setText("Generar Comentario");
        pnlGenerar.add(lblestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 56, 231, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(37, 45, 223));
        jLabel4.setText("Comentario");
        pnlGenerar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 179, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(37, 45, 223));
        jLabel2.setText("Fecha :");
        pnlGenerar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 107, 58, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(37, 45, 223));
        jLabel3.setText("Tipo: ");
        pnlGenerar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 107, -1, 40));

        txtcontenidoRetro.setColumns(20);
        txtcontenidoRetro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtcontenidoRetro.setLineWrap(true);
        txtcontenidoRetro.setRows(5);
        txtcontenidoRetro.setWrapStyleWord(true);
        txtcontenidoRetro.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1)));
        txtcontenidoRetro.setCaretColor(new java.awt.Color(153, 153, 153));
        txtcontenidoRetro.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtcontenidoRetro.setSelectionColor(new java.awt.Color(204, 204, 204));
        jScrollPane4.setViewportView(txtcontenidoRetro);

        pnlGenerar.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 216, 614, 180));

        lblFecha.setForeground(new java.awt.Color(0, 0, 0));
        pnlGenerar.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 107, 88, -1));

        btnAceptarGenerar.setBackground(new java.awt.Color(204, 204, 204));
        btnAceptarGenerar.setText("Aceptar");
        btnAceptarGenerar.setBackgroundHover(new java.awt.Color(0, 153, 0));
        btnAceptarGenerar.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnAceptarGenerar.setForegroundText(new java.awt.Color(0, 0, 0));
        btnAceptarGenerar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAceptarGenerar.setIconTextGap(29);
        btnAceptarGenerar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CHECK_BOX);
        btnAceptarGenerar.setPaddingLeft(15);
        btnAceptarGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarGenerarActionPerformed(evt);
            }
        });
        pnlGenerar.add(btnAceptarGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 429, 182, -1));

        lblFecha2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pnlGenerar.add(lblFecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 99, 32));

        pnlSliderRetro.add(pnlGenerar, "card2");

        btnVolver.setBackground(new java.awt.Color(204, 204, 204));
        btnVolver.setText("Volver");
        btnVolver.setBackgroundHover(new java.awt.Color(0, 108, 255));
        btnVolver.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnVolver.setForegroundText(new java.awt.Color(0, 0, 0));
        btnVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolver.setIconTextGap(29);
        btnVolver.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.KEYBOARD_ARROW_LEFT);
        btnVolver.setPaddingLeft(15);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSliderRetro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSliderRetro, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarRetroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarRetroKeyReleased
        try {
            actualizarLista(txtBuscarRetro.getText());
        } catch (SQLException ex) {
            Logger.getLogger(pnlComentariosSolicitante.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_txtBuscarRetroKeyReleased

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
       
        limpiarEntradas();
        this.pnlSliderRetro.setPanelNormal(pnlTablaRetro);
        btnVolver.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnSugerenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSugerenciasActionPerformed
        try {
            btnSugerencias.setSelected(true);
            btnReclamos.setSelected(false);
            this.tipo = "Sugerencia";
            actualizarLista("");
        } catch (SQLException ex) {
            Logger.getLogger(pnlComentariosSolicitante.class.getName())
                    .log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSugerenciasActionPerformed

    private void btnReclamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReclamosActionPerformed
        try {
            btnSugerencias.setSelected(false);
            btnReclamos.setSelected(true);
            this.tipo = "Reclamo";
            actualizarLista("");
        } catch (SQLException ex) {
            Logger.getLogger(pnlComentariosSolicitante.class.getName())
                    .log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReclamosActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        this.pnlSliderRetro.setPanelNormal(pnlGenerar);
        btnVolver.setVisible(true);
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnVisualizarRetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarRetroActionPerformed

        int indice = tablaRetro.getSelectedRow();        
        if(indice != -1)
        {
            Mensaje mensaje = listaRetro.get(indice);
            llenarDatos(mensaje);
            this.pnlSliderRetro.setPanelNormal(pnlGenerar);
            btnVolver.setVisible(true);
        }
        else{        
            JOptionPane.showMessageDialog(null,"Seleccione un comentario de la lista");
        }
    }//GEN-LAST:event_btnVisualizarRetroActionPerformed

    private void btnAceptarGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarGenerarActionPerformed
        try {
            String tipoRetro = cbxTipo.getSelectedItem().toString();
            String contenido = txtcontenidoRetro.getText();
            if(!contenido.isEmpty()){                
                cod= servicio.getCodigo(tipoRetro,user.getDni());                        
                servicio.insertarRetroalimentacion(cod,tipoRetro,contenido
                        ,user.getDni());
                
                actualizarLista("");
                JOptionPane.showMessageDialog(null,"Se agrego correctamente el "
                        + "comentario");
            }
            else{
                JOptionPane.showMessageDialog(null,"Completa el campo comentario");
            }
           
        } catch (SQLException ex) {
            Logger.getLogger(pnlComentariosSolicitante.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAceptarGenerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconOne btnAceptarGenerar;
    private RSMaterialComponent.RSButtonMaterialIconOne btnGenerar;
    private RSMaterialComponent.RSButtonMaterialIconOne btnReclamos;
    private RSMaterialComponent.RSButtonMaterialIconOne btnSugerencias;
    private RSMaterialComponent.RSButtonMaterialIconOne btnVisualizarRetro;
    private RSMaterialComponent.RSButtonMaterialIconOne btnVolver;
    private RSMaterialComponent.RSComboBoxMaterial cbxTipo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private rojeru_san.rsdate.RSLabelFecha lblFecha;
    private javax.swing.JLabel lblFecha2;
    private javax.swing.JLabel lblestado;
    private javax.swing.JPanel pnlGenerar;
    private rojerusan.RSPanelEffect pnlSliderRetro;
    private javax.swing.JPanel pnlTablaRetro;
    private RSMaterialComponent.RSTableMetroCustom tablaRetro;
    private RSMaterialComponent.RSTextFieldMaterialIcon txtBuscarRetro;
    private javax.swing.JTextArea txtcontenidoRetro;
    // End of variables declaration//GEN-END:variables
     public void cargarUsuario(Usuario user) throws SQLException{
        this.user = user;        
        listaRetro = new ArrayList<>();
        actualizarLista("");       
    } 

    private void actualizarLista(String buscar) throws SQLException {       
        listaRetro = new ArrayList<>();
        this.servicio.listarRetroAlimentacion(tablaRetro,user.getDni(),buscar
                ,this.tipo,listaRetro);
    }
    private void limpiarEntradas(){
        lblestado.setText("Generar Comentario");
        cbxTipo.setSelectedIndex(0);
        txtcontenidoRetro.setText("");
        txtcontenidoRetro.setEnabled(true);
        lblFecha.setVisible(true);
        lblFecha2.setVisible(false);
        btnAceptarGenerar.setVisible(true);
    }
    private void llenarDatos(Mensaje mensaje) {
        lblestado.setText("Ver Comentario");
        cbxTipo.setSelectedItem(mensaje.getTipo());
        txtcontenidoRetro.setEnabled(false);
        txtcontenidoRetro.setText(mensaje.getContenido());
        lblFecha.setVisible(false);
        lblFecha2.setVisible(true);
        lblFecha2.setText(mensaje.getFecha().toString());
        btnAceptarGenerar.setVisible(false);
    }

}
