/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesGraficas.Login;

import Config.ConexionBaseDeDatos;
import Entidades.*;

/**
 *
 * @author chave
 */
public class CrearCuenta extends javax.swing.JFrame {

    /**
     * Creates new form CrearCuenta
     */
    IniciarSesion login;
    public CrearCuenta(IniciarSesion login) {
        initComponents();
        this.login= login;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblcrearCuenta = new javax.swing.JLabel();
        lblcorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lbldni = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblFechaNac = new javax.swing.JLabel();
        txtFechaNacimiento = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblnombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        lblcontraseña = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        txtCodigo = new javax.swing.JTextField();
        btnMinimize = new javax.swing.JLabel();
        labelIcon1 = new necesario.LabelIcon();
        btnClose = new javax.swing.JLabel();
        lblfoto = new javax.swing.JLabel();
        btnSeleccionarFoto = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JLabel();
        btnBuscarDni = new javax.swing.JLabel();
        btnSeleccionarUbicacion = new javax.swing.JLabel();
        btbEnviarCodigo = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(12, 140, 233));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcrearCuenta.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        lblcrearCuenta.setForeground(new java.awt.Color(30, 30, 30));
        lblcrearCuenta.setText("Crear Cuenta");
        jPanel1.add(lblcrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lblcorreo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblcorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblcorreo.setText("Correo");
        jPanel1.add(lblcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        txtCorreo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCorreo.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 2));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 300, 32));

        lbldni.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lbldni.setForeground(new java.awt.Color(255, 255, 255));
        lbldni.setText("Ingrese Dni:");
        jPanel1.add(lbldni, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        lblApellidos.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidos.setText("Apellidos");
        jPanel1.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        txtApellidos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtApellidos.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 2));
        txtApellidos.setEnabled(false);
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 300, 32));

        lblFechaNac.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblFechaNac.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaNac.setText("Fecha de Nacimiento");
        jPanel1.add(lblFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        txtFechaNacimiento.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtFechaNacimiento.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 2));
        txtFechaNacimiento.setEnabled(false);
        jPanel1.add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 300, 32));

        lblDireccion.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccion.setText("Dirección");
        jPanel1.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        txtDireccion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtDireccion.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 2));
        txtDireccion.setEnabled(false);
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 300, 32));

        lblnombres.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblnombres.setForeground(new java.awt.Color(255, 255, 255));
        lblnombres.setText("Nombres ");
        jPanel1.add(lblnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        txtNombres.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNombres.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 2));
        txtNombres.setEnabled(false);
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 300, 32));

        lblCodigo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigo.setText("Ingrese Código");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, 20));

        txtDni.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtDni.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 2));
        jPanel1.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 190, 32));

        lblcontraseña.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblcontraseña.setForeground(new java.awt.Color(255, 255, 255));
        lblcontraseña.setText("Contraseña");
        jPanel1.add(lblcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));

        txtCelular.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCelular.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 2));
        jPanel1.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 300, 32));

        lblCelular.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblCelular.setForeground(new java.awt.Color(255, 255, 255));
        lblCelular.setText("Celular");
        jPanel1.add(lblCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, 20));

        txtContraseña.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 2));
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, 300, 30));

        txtCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCodigo.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 2));
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 300, 32));

        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/32wtminimize-sign.png"))); // NOI18N
        jPanel1.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, -1, -1));

        labelIcon1.setForeground(new java.awt.Color(255, 255, 255));
        labelIcon1.setFontSize(30.0F);
        labelIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LOCATION_ON);
        labelIcon1.setPreferredSize(new java.awt.Dimension(35, 35));
        jPanel1.add(labelIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 30, 30));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/32wtclose.png"))); // NOI18N
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        lblfoto.setBackground(new java.awt.Color(255, 255, 255));
        lblfoto.setOpaque(true);
        jPanel1.add(lblfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 100, 120));

        btnSeleccionarFoto.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnSeleccionarFoto.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSeleccionarFoto.setText("Seleccionar Foto");
        btnSeleccionarFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btnSeleccionarFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnSeleccionarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 180, 40));

        btnAceptar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 250, 40));

        btnBuscarDni.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnBuscarDni.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarDni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarDni.setText("Buscar");
        btnBuscarDni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btnBuscarDni.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnBuscarDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 100, 40));

        btnSeleccionarUbicacion.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnSeleccionarUbicacion.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarUbicacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSeleccionarUbicacion.setText("Seleccionar Ubicación");
        btnSeleccionarUbicacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btnSeleccionarUbicacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnSeleccionarUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 270, 50));

        btbEnviarCodigo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btbEnviarCodigo.setForeground(new java.awt.Color(255, 255, 255));
        btbEnviarCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btbEnviarCodigo.setText("Enviar Código");
        btbEnviarCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btbEnviarCodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btbEnviarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 230, 40));

        btnCancelar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 250, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.dispose();
        login.setVisible(true);        
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btbEnviarCodigo;
    private javax.swing.JLabel btnAceptar;
    private javax.swing.JLabel btnBuscarDni;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JLabel btnSeleccionarFoto;
    private javax.swing.JLabel btnSeleccionarUbicacion;
    private javax.swing.JPanel jPanel1;
    private necesario.LabelIcon labelIcon1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFechaNac;
    private javax.swing.JLabel lblcontraseña;
    private javax.swing.JLabel lblcorreo;
    private javax.swing.JLabel lblcrearCuenta;
    private javax.swing.JLabel lbldni;
    private javax.swing.JLabel lblfoto;
    private javax.swing.JLabel lblnombres;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
